package models

// User public model generated by bindu
type User struct {
	Username string `gorm:"type:varchar(20);unique_index;not null" form:"username" json:"username" binding:"required"`
	Password string `form:"password" json:"password" binding:"required" json:"-"`
	Role     string
	DefaultProperties
}
